# Generated by Django 4.0.6 on 2022-09-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catg_id',
            new_name='cat_desc',
        ),
    ]
