# Generated by Django 4.0.6 on 2022-09-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/placeholder.png', upload_to='images'),
        ),
    ]
