# Generated by Django 4.0.6 on 2022-10-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
