# Generated by Django 4.0.6 on 2022-11-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userZipCode',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
