# Generated by Django 4.0.6 on 2022-11-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_profile_userzipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userNameOnCreditCard',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userCreditCardNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
