# Generated by Django 4.0.6 on 2022-11-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_profile_usernameoncreditcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userCity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userMobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userStreetNumber',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userZipCode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
