# Generated by Django 4.0.6 on 2022-11-03 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_profile_birth_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_det',
        ),
    ]
