# Generated by Django 4.0.6 on 2022-11-03 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_delete_order_det'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_det',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('prod_quantity', models.IntegerField()),
                ('order_subtotal', models.IntegerField()),
                ('order_discount', models.IntegerField()),
                ('order_total', models.IntegerField()),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('prod_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
            ],
        ),
    ]
