# Generated by Django 4.0.6 on 2022-11-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_order_det'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order_det',
            name='order_discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order_det',
            name='order_subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order_det',
            name='order_total',
            field=models.FloatField(),
        ),
    ]
